test_average (__main__.TestExercice) ... ok
test_to_celsius (__main__.TestExercice) ... FAIL
test_to_degrees (__main__.TestExercice) ... FAIL
test_to_farenheit (__main__.TestExercice) ... FAIL
test_to_radians (__main__.TestExercice) ... ok

======================================================================
FAIL: test_to_celsius (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 74, in test_to_celsius
    'Mauvais calcul de farenheit -> celsius'
AssertionError: Lists differ: [-57.599999999999994, -102.6, 754.1999999999999] != [-17.77777777777778, -31.666666666666664, 232.77777777777777]

First differing element 0:
-57.599999999999994
-17.77777777777778

- [-57.599999999999994, -102.6, 754.1999999999999]
+ [-17.77777777777778, -31.666666666666664, 232.77777777777777] : Mauvais calcul de farenheit -> celsius

======================================================================
FAIL: test_to_degrees (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 62, in test_to_degrees
    'Mauvais calcul de radians -> degres'
AssertionError: Lists differ: [(114.59155902616465, 54.591559026164646, 1[194 chars]067)] != [(79.0980174562859, 5.881047377154118, 29.6[197 chars]998)]

First differing element 0:
(114.59155902616465, 54.591559026164646, 114.59155902616465)
(79.0980174562859, 5.881047377154118, 29.612494192724625)

- [(114.59155902616465, 54.591559026164646, 114.59155902616465),
-  (-229.1831180523293, 10.816881947670709, 3370.8168819476705),
-  (286.4788975654116, 46.478897565411614, 286.4788975654116),
-  (234.3397382085067, 54.3397382085067, 234.3397382085067)]
+ [(79.0980174562859, 5.881047377154118, 29.612494192724625),
+  (-278.1960349125718, 48.23790524569176, 0.7750116145507491),
+  (257.74504364071475, -15.297381557114704, 44.031235481811564),
+  (213.95544569810457, -2.673258113725865, 23.057550624127998)] : Mauvais calcul de radians -> degres

======================================================================
FAIL: test_to_farenheit (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 86, in test_to_farenheit
    'Mauvais calcul de celsius -> farenheit'
AssertionError: Lists differ: [32.0, -13.0, 843.8] != [32.0, -13.0, 843.8000000000001]

First differing element 2:
843.8
843.8000000000001

- [32.0, -13.0, 843.8]
+ [32.0, -13.0, 843.8000000000001]
?                    ++++++++++++
 : Mauvais calcul de celsius -> farenheit

----------------------------------------------------------------------
Ran 5 tests in 0.004s

FAILED (failures=3)
